#!/usr/bin/env bash
# (임시) 체육센터 1차: 생활체육포털 목록, 체육센터·체육회 첫 화면
f() { python scripts/dev_fetch.py "$@" || true; }
f portal_assoc "https://www.busan.go.kr/sports/main/28"
f portal_main "https://www.busan.go.kr/sports/main"
f portal_fac "https://www.busan.go.kr/sports/main/30"
f bnsc "http://www.bnsc.or.kr/"
f sportsbusan "http://www.sports.busan.kr/"
f jsports "https://www.jsports.or.kr/"
f bjsports "http://www.busanjingu-sports.or.kr/"
f sahak "https://www.sahaksports.or.kr/"
f bukgusports "http://bukgusports.com/"
f yeonje "https://sports.yeonje.go.kr/"
f gjsports "https://www.gjsports.go.kr/"
f sysports "https://www.sysports.or.kr/"
f saba "https://www.saba.or.kr/"
f hdswim "http://www.haeundaeswim.com/"
f gs7330 "https://www.gs7330.com/"
f jg7330 "http://www.bsjgsc7330.co.kr/"
f gscsports "https://www.gscsports.or.kr/"
f sportssy "http://www.sportssy.or.kr/"
f sahasports "http://sahasports.or.kr/"
f sasangsports "https://sasangsports.com/"
f bngsports "http://www.bngsports.or.kr/"
f seogusports "http://bsseogusports.or.kr/"
f dongnae_sports "https://sports.dongnae.go.kr/"
