#!/usr/bin/env bash
# (임시) 복지관 5차: 노인복지관 공지·채용 목록 + 첫 화면 다시 + 장애인시설 목록
f() { python scripts/dev_fetch.py "$@" || true; }
f sb_busanjin "https://www.chambokji.org/SW_bbs/notice/list.php?zipEncode==i2BQ91vt1drjrMCH9MyMetpSfMvWLME"
f sb_city_rec "http://www.youngsilver.or.kr/bbs/board.php?bo_table=recruit"
f sb_city_not "http://www.youngsilver.or.kr/bbs/board.php?bo_table=notice"
f sb_dasarang "http://www.xn--9i1b2b12rnnlbwc3yf.org/board/bbs/board.php?bo_table=notice"
f sb_gangseo "http://www.senior1004.co.kr/community1.html"
f sb_geumjeong "https://www.geumjeongsilver.kr/SW_bbs/notice/list.php?zipEncode==etpLrxydrMCH9MyMu2yPr3BU91vt1drjrMCH9MyMetpSfMvWLME"
f sb_gwangan "https://www.gasenior.org/SW_bbs/notice/list.php?zipEncode==etpLrxydrMCH9MyMu2yPr3BU91vt1drjrMCH9MyMetpSfMvWLME"
f sb_jasungdae "http://jasungdae.or.kr/sub5_1.html"
f sb_junggu "http://www.junggusilver.or.kr/SW_bbs/notice/list.php?zipEncode==etpLrxydrMCH9MyMu2yPr3BU91vt1drjrMCH9MyMetpSfMvWLME"
f sb_munhyeon "http://moon9988.or.kr/SW_bbs/notice/list.php?zipEncode==u2yPr3BU91vt1drjrMCH9MyMetpSfMvWLME"
f sb_myeongji_rec "http://mjnoin.ai-sw.net/bbs/board.php?bo_table=reqruit"
f sb_ojin_rec "http://ojin.saem.or.kr/community/guest/"
f sb_sasang_x "http://www.sasang-senior.or.kr/SW_bbs/notice/list.php?zipEncode=Xi2BQ91vt1drjrMCH9MyMetpSfMvWLME"
f sb_sasang_y "http://www.sasang-senior.or.kr/SW_bbs/notice/list.php?zipEncode=Yi2BQ91vt1drjrMCH9MyMetpSfMvWLME"
f sb_silverbell "http://www.xn--hk3bqct1u.kr/html/index.php?pageNum=005002000"
f sb_suyeong "https://6070.bulgukto.or.kr/SW_bbs/notice/list.php?zipEncode==i2BQ91vt1drjrMCH9MyMetpSfMvWLME"
f sb_yeongdo "http://www.youngdosenior.or.kr/SW_bbs/notice/list.php?zipEncode==etpLrxydrMCH9MyMu2yPr3BU91vt1drjrMCH9MyMetpSfMvWLME"
f sb_yeonje "http://www.yjsilver.com/board/notice/lists"
f sb_seogu "https://www.bssgsenior.or.kr/sub_menu5/list.asp?board_idx=D85311AC6B3572390A958C8A62F9AB88D2C076CD31C20209F1632906D4733356&s_gubun=b"
f sm_namgu "http://www.ngswc.or.kr/main/main.php"
f sm_bumin "https://www.bmsenior.org/index.php"
f sm_saha "https://sahasilver.org/main.php"
f sm_gijang "https://www.gijangcmc.or.kr/nosasa/main/main.asp"
f dis_list "https://bsrehab.or.kr/facilities/facilities.php"
f dis_rehab "https://www.rehabcenter.or.kr/"
f dis_white "https://www.newwhite.or.kr/"
f dis_haeundae "http://togetherhaeundae.or.kr/"
